// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: config.sql

package database

import (
	"context"
)

const getActiveUserID = `-- name: GetActiveUserID :one
SELECT value 
FROM config 
WHERE key = 'active_user_id'
`

func (q *Queries) GetActiveUserID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserID)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setActiveUserID = `-- name: SetActiveUserID :exec
INSERT INTO config (key, value) 
VALUES ('active_user_id', ?) 
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetActiveUserID(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setActiveUserID, value)
	return err
}
