// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: history.sql

package database

import (
	"context"
)

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO history (user_id, point, reason)
VALUES (?, ?, ?)
`

type InsertHistoryParams struct {
	UserID int64
	Point  int64
	Reason string
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory, arg.UserID, arg.Point, arg.Reason)
	return err
}
