// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: history.sql

package database

import (
	"context"
)

const listHistory = `-- name: ListHistory :many
SELECT id, point, reason, date FROM history
`

func (q *Queries) ListHistory(ctx context.Context) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Point,
			&i.Reason,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
