// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type History struct {
	ID     interface{}
	Point  int64
	Reason string
	Date   int64
}

type Point struct {
	ID    interface{}
	Total sql.NullInt64
	Goal  int64
}
